spring.application.name=sangoma_link

spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.profiles.active=dev
spring.servlet.multipart.max-file-size= 50MB
springdoc.default-produces-media-type= application/json

server.servlet.context-path = /api/v1/

#image.directory.static=classpath:/static/images/
#image.directory.uploads=/static/images/

